// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 対応するプロバイダーAPIの方言。現状はOpenAI互換チャットコンプリーションAPIのみ
 * (architecture.md 2節)。将来プロバイダーを追加する際はここにバリアントを足す。
 */
export type ApiFormat = "open_ai_compat";
