// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiFormat } from "./ApiFormat";

/**
 * 登録フォームの方言の選択肢1つ。
 */
export type ApiFormatChoice = { api_format: ApiFormat, default_base_url: string, };
