// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentKind } from "./AttachmentKind";

/**
 * 画面に渡す形。テキストの本文と実体は載せない(開いたときに別のコマンドで引く)。
 */
export type AttachmentView = { id: number, original_name: string, mime_type: string, kind: AttachmentKind, size_bytes: number, };
