// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Delivery } from "./Delivery";

export type AttachmentDeliveries = { text: Delivery, image: Delivery, other: Delivery, };
