// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Delivery } from "./Delivery";

/**
 * 種別ごとの渡し方。`None`は、モデルが未選択で決まらない。
 */
export type AttachmentDeliveries = { text: Delivery | null, image: Delivery | null, other: Delivery | null, };
