// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * プロバイダーの一覧から取得したモデル1件(Issue #33)。
 */
export type AvailableModel = { 
/**
 * サーバーが返したままの名前。登録するときに送り返す。
 */
name: string, label: string, };
