// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 登録フォームで、ベースURLの欄の下に出すヒント。登録は止めない。
 */
export type BaseUrlHint = "version_path_included";
