// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * モデルの能力のうち、対応の有無で表すもの。
 */
export type Capability = "image" | "tools" | "thinking";
