// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 発言が属する会話。`messages.task_id`がNULLなら総合チャット(data-model.md messages)。
 * `Option<i64>`で持たないのは、渡し忘れの`None`が総合チャットへの書き込みに化けるのを
 * 型で防ぐため(tools.md 1節が修正した「対象の取り違え」と同種の事故)。
 * 画面とは`{"kind":"general"}`・`{"kind":"task","task_id":1}`の形でやり取りする。
 */
export type Chat = { "kind": "general" } | { "kind": "task", "task_id": number };
