// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelChoice } from "./ModelChoice";
import type { SelectedModel } from "./SelectedModel";

/**
 * チャット入力欄の下のモデル選択・思考の強さ選択(Issue #64)。設定画面の[`SettingsView`]
 * とは別に持ち、選ぶのに要るものだけを渡す。
 */
export type ChatModelsView = { 
/**
 * 一覧に出すモデル(設定画面で表示にしたもの)。プロバイダーの登録順、その中はモデルの
 * 登録順。
 */
choices: Array<ModelChoice>, 
/**
 * チャットで使うモデル。一覧から隠したモデルでも、使っていれば入る。
 */
selected: SelectedModel | null, };
