// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * データディレクトリを決められない・使えない理由。GUIは起動時に開けなかった理由として
 * 画面へ渡し、画面は種類で文言を選ぶ。パスは利用者が置き場所を直すのに要るので載せる。
 */
export type DataDirError = { "kind": "no_executable", reason: string, } | { "kind": "temporary_dir", dir: string, } | { "kind": "no_app_dir", reason: string, } | { "kind": "unusable", dir: string, reason: string, } | { "kind": "app_dir_unusable", dir: string, reason: string, } | { "kind": "database", dir: string, reason: string, };
