// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 添付をモデルへどう渡すか。履歴の組み立てと、画面が添付に出す警告
 * (`settings::ChatModelsView`)の両方がこれで決める。
 */
export type Delivery = "content" | "image" | "name_only";
