// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 窓にファイルが落とされたことを画面へ知らせる形。パスは渡さない。
 */
export type DropNotice = { drop_id: number, 
/**
 * 落とした順のファイル名。読むときは、この並びの位置で指す。
 */
names: Array<string>, };
