// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 書き出す先。画面は受け取って、押せる操作と結果の文言を出し分ける。
 */
export type ExportTarget = "folder" | "chosen_file";
