// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportSummary } from "./ExportSummary";

/**
 * 書き出しの操作の結果。
 */
export type ExportOutcome = { "status": "written", summary: ExportSummary, } | { "status": "saved", summary: ExportSummary, } | { "status": "cancelled" } | { "status": "left_incomplete", reason: string, };
