// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 書き出しの結果。
 */
export type ExportSummary = { 
/**
 * 書き出したフォルダの名前(`root`の直下)。
 */
folder: string, tasks: number, attachments: number, 
/**
 * 実体を読めない・書けないために同梱できなかった添付の数。
 */
missing_attachments: number, };
