// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputRejection } from "./InputRejection";

/**
 * 画面の入力を受け取る操作の結果。受け付けなかった理由([`CoreError::Rejected`])は失敗に
 * せず種類で返し、画面は欄の近くに出す。それ以外の失敗はコマンドの失敗のまま。
 */
export type FormOutcome<T> = { "status": "accepted", value: T, } | { "status": "rejected", reasons: Array<InputRejection>, };
