// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Language } from "./Language";

/**
 * 一般設定。既定値を持つものは、`ToolSettingsView`と同じく設定値(未設定は`None`)と
 * 未設定時の既定値の両方を渡す。
 */
export type GeneralSettingsView = { system_prompt: string | null, task_chat_system_prompt: string | null, 
/**
 * 表示言語の既定の文面(`default_task_opening_message`も同じ)。
 */
default_task_chat_system_prompt: string, task_opening_message: string | null, default_task_opening_message: string, response_timeout_secs: number | null, default_response_timeout_secs: number, 
/**
 * 未設定なら既定の言語に解決した値。画面は「未設定」を扱わない。
 */
language: Language, };
