// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NumberField } from "./NumberField";

/**
 * 受け付けなかった理由の1つ。
 */
export type InputRejection = { "kind": "not_positive_integer", field: NumberField, } | { "kind": "number_too_large", field: NumberField, max: number, } | { "kind": "mcp_server_name_required" } | { "kind": "mcp_server_name_invalid", max_chars: number, } | { "kind": "mcp_server_name_taken", name: string, } | { "kind": "url_required" } | { "kind": "header_line_invalid", line_no: number, };
