// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 表示言語。値は言語ファイルの名前(`lang/{code}.json`)と、画面の`lang`属性に使う。
 */
export type Language = "ja" | "en";
