// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkVerdict } from "./LinkVerdict";

/**
 * 確認ダイアログに出す内容。`url`は受け取った文字列をそのまま返す(表示用)。
 */
export type LinkInspection = { url: string, verdict: LinkVerdict, 
/**
 * `verdict`から決まる。「開く」を出すかどうかの判断を画面側に写さないため、
 * 判定結果として一緒に渡す。
 */
can_open: boolean, 
/**
 * 書かれたホストと実際の移動先ホストが食い違う場合だけ、移動先のURL全体
 * (ホストはpunycode)。見た目の似た文字によるなりすまし(ホモグラフ)や、
 * `%65vil.com`・全角英字のような、ブラウザが変換してから向かう書き方を見分けるため。
 */
real_url: string | null, 
/**
 * URLがユーザー情報(`@`より前)を含む場合だけ、実際の移動先ホスト。
 * `https://google.com@evil.com/`のように、`@`より前をサイト名に見せかける手口があるため。
 */
userinfo_host: string | null, };
