// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 開いてよいかどうかと、その理由。
 */
export type LinkVerdict = { "kind": "web" } | { "kind": "mail" } | { "kind": "unreadable" } | { "kind": "scheme_blocked", scheme: string, };
