// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpEndpointView = { "transport": "streamable_http", url: string, header_names: Array<string>, };
