// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpEndpointView = { "transport": "stdio", command: string, args: Array<string>, env_names: Array<string>, } | { "transport": "streamable_http", url: string, header_names: Array<string>, };
