// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpEndpointView } from "./McpEndpointView";
import type { McpToolView } from "./McpToolView";

export type McpServerView = { id: string, name: string, enabled: boolean, endpoint: McpEndpointView, enabled_tools: Array<string>, 
/**
 * 画面に出すツール一覧。取得済みの一覧に、そこに無い有効化済みのツールを足したもの
 * (再起動直後の未取得の間も、有効化済みのツールを確かめて外せるように)。
 */
tools: Array<McpToolView>, tools_fetched: boolean, };
