// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingsView } from "./SettingsView";

/**
 * [`Settings::add_mcp_server`]の結果。`tools_error`は、登録のあとのツール一覧の取得に
 * 失敗した理由(画面は追加したサーバーのカードに出す)。
 */
export type McpServerAdded = { settings: SettingsView, server_id: string, tools_error: string | null, };
