// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 設定画面へ渡すツール1件。引数スキーマは表示に使わないので渡さない。
 */
export type McpToolView = { 
/**
 * サーバーが返したままの名前。有効化を切り替えるときの鍵として送り返すだけで、
 * 画面には描かない(描くのは`label`)。
 */
name: string, 
/**
 * 画面に出す名前と説明。サーバーが書いた文字列なので、見えない文字を除いた写しを渡す。
 */
label: string, description: string | null, 
/**
 * モデルへ公開できるか(名前と引数スキーマ。`tools::external::is_exposable`)。公開できない
 * ツールは有効にできない。
 */
exposable: boolean, };
