// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 会話をまたいで共有する、利用者についての事実1件。どの会話にも属さない。
 */
export type Memory = { id: number, content: string, created_at: string, updated_at: string, };
