// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentView } from "./AttachmentView";
import type { Kind } from "./Kind";
import type { Role } from "./Role";

export type Message = { id: number, task_id: number | null, role: Role, content: string, kind: Kind, source: string | null, error_kind: string | null, error_detail: string | null, turn_id: string | null, attempt_no: number | null, created_at: string, 
/**
 * 発言に付いた添付。付けた順。
 */
attachments: Array<AttachmentView>, };
