// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelChoice = { provider_id: string, provider_name: string, 
/**
 * 選ぶときに送り返す名前。画面に出すのは`label`([`ModelView`]と同じ)。
 */
model: string, label: string, };
