// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelCapabilities } from "./ModelCapabilities";

/**
 * モデル表の1行(Issue #65)。能力は解決済みの値を渡し、画面は3層の解決を自前で行わない。
 */
export type ModelView = { 
/**
 * 登録した名前。操作の鍵として送り返すだけで、画面には描かない(描くのは`label`)。
 */
name: string, 
/**
 * 画面に出す名前。プロバイダーの一覧から選んだ名前はサーバーが書いた文字列なので、
 * 見えない文字を除いた写しを渡す(architecture.md 10節)。
 */
label: string, visible: boolean, capabilities: ModelCapabilities, 
/**
 * 手動設定が無いとき(自動検出 → 既定値)のコンテキスト長。入力欄のプレースホルダに出す。
 */
default_context_length: number, 
/**
 * 能力に手動設定がある(「初期値に戻す」を出す)。
 */
overridden: boolean, };
