// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * サーバー追加フォームからの入力。`McpEndpoint`と同じく、接続方式ごとに必要な値だけを
 * 受け取る。組の2つ目は秘密情報の値で、保存後は`key_ref`に置き換わる。値を含むため
 * `Debug`は付けない(ログに出す経路を作らない)。
 */
export type NewMcpEndpoint = { "transport": "streamable_http", url: string, headers: Array<[string, string]>, };
