// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 数値の欄のどれか。CLIのエラー文に名前を出すのと、画面がどの欄の下に出すかを決めるのに使う。
 */
export type NumberField = "response_timeout_secs" | "max_rounds_per_turn" | "total_timeout_secs" | "context_length";
