// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolExecutionView } from "./ToolExecutionView";

/**
 * ターンの中身の1要素の表示。`round`は1始まりのラウンドの番号。
 */
export type PartView = { "type": "reasoning", round: number, text: string, } | { "type": "text", round: number, text: string, } | { "type": "tool", round: number, id: number, execution: ToolExecutionView, };
