// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 画面へ渡す上限。種別は中身を読むまで分からないので、種別ごとの上限は渡さず
 * (預けたときの判定の結果として返る)、どの種別でも受け付けない大きさだけを渡す。
 */
export type PickingLimits = { largest_bytes: number, per_message: number, };
