// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiFormat } from "./ApiFormat";
import type { ModelView } from "./ModelView";

export type ProviderView = { id: string, name: string, api_format: ApiFormat, base_url: string, models: Array<ModelView>, active_model: string | null, has_api_key: boolean, 
/**
 * モデルの能力を推論サーバーに問い合わせられる(「能力を検出」を出す)。
 */
can_detect_capabilities: boolean, 
/**
 * このプロバイダーをアクティブにしているが、組み立てられない理由。
 */
error: string | null, };
