// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 思考の強さ。リクエストでの書き方は方言ごとにアダプタが決める。
 */
export type ReasoningEffort = "off" | "low" | "medium" | "high";
