// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ファイルを受け取ったことを画面へ知らせる形。パスは渡さない。
 */
export type ReceivedFiles = { batch_id: number, 
/**
 * 受け取った順のファイル名。読むときは、この並びの位置で指す。
 */
names: Array<string>, };
