// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 返信を消してから生成し直す操作([`edit_user_message`]・[`retry_reply`])の結果。
 */
export type Regeneration = { "status": "generated" } | { "status": "unavailable", error_kind: string, };
