// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentKind } from "./AttachmentKind";

export type Rejection = { "reason": "too_large", kind: AttachmentKind, limit_bytes: number, };
