// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinishReason } from "./FinishReason";
import type { ToolArguments } from "./ToolArguments";

/**
 * アダプタ層が上位に渡す形は完成した応答1つではなくイベントの並び。ストリーミングしない
 * プロバイダーも各イベントを1回ずつ渡せば同じ経路に乗る([`LlmAdapter::send`])。
 */
export type ResponseEvent = { "type": "text_delta", text: string, } | { "type": "reasoning_delta", text: string, } | { "type": "tool_call", 
/**
 * プロバイダが払い出した呼び出しID。1応答に複数のツール呼び出しが載る場合に
 * 結果と対応付けるために保持する。払い出さないプロバイダもあるためOption。
 */
id: string | null, name: string, arguments: ToolArguments, } | { "type": "done", finish_reason: FinishReason, };
