// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentDeliveries } from "./AttachmentDeliveries";
import type { ReasoningEffort } from "./ReasoningEffort";

export type SelectedModel = { 
/**
 * 思考に対応する(3層で解決済み)。対応しなければ思考の強さは選べない。
 */
thinking: boolean, reasoning_effort: ReasoningEffort, 
/**
 * 送る発言の添付を、種別ごとにモデルへどう渡すか(`attachments::delivery`)。
 * 画面は`name_only`の種別に警告を出す(送信は止めない)。
 */
attachments: AttachmentDeliveries, provider_id: string, provider_name: string, 
/**
 * 選ぶときに送り返す名前。画面に出すのは`label`([`ModelView`]と同じ)。
 */
model: string, label: string, };
