// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeneralSettingsView } from "./GeneralSettingsView";
import type { McpServerView } from "./McpServerView";
import type { ProviderView } from "./ProviderView";
import type { ToolSettingsView } from "./ToolSettingsView";

export type SettingsView = { 
/**
 * 起動時に設定ファイルを読めなかった理由。あれば設定は保存されない。
 */
config_error: string | null, general: GeneralSettingsView, tools: ToolSettingsView, providers: Array<ProviderView>, active_provider_id: string | null, mcp_servers: Array<McpServerView>, 
/**
 * サーバー識別子の長さの上限。画面は入力欄の上限と案内文に使い、値を写さない。
 */
mcp_server_name_max_chars: number, };
