// This file was generated by a test in scitl-core (`i18n::tests::export_shared_constants`). Do not edit this file manually.
import type { Language } from "./Language";

/** 未設定のときの表示言語で、すべてのキーを持つ正本(`i18n::Language::DEFAULT`)。 */
export const DEFAULT_LANGUAGE: Language = "ja";

/** エラー発言の文言のキーの前置き(`orchestration::turn_error::MESSAGE_KEY_PREFIX`)。 */
export const TURN_ERROR_KEY_PREFIX = "turn_error.";
