// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentKind } from "./AttachmentKind";

/**
 * [`Staged::stage`]の結果。
 */
export type StageOutcome = { "status": "staged", token: string, kind: AttachmentKind, mime_type: string, size_bytes: number, } | { "status": "rejected", } & ({ "reason": "too_large", kind: AttachmentKind, limit_bytes: number, } | { "reason": "not_a_file" } | { "reason": "too_many", limit: number, } | { "reason": "unsupported" } | { "reason": "image_unreadable" });
