// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Task } from "./Task";

/**
 * [`create_task`]の結果。
 */
export type TaskCreation = { "status": "created", task: Task, opening_error: string | null, } | { "status": "unavailable", error_kind: string, };
