// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Task } from "./Task";
import type { TurnEvent } from "./TurnEvent";

/**
 * [`create_task`]をIPCで呼ぶときに画面へ送る途中経過。作ったタスクを聞き取りの途中経過と
 * 同じ経路で先に送る(経路を分けると、届く順が保証されない)。
 */
export type TaskOpeningEvent = { "type": "created", task: Task, } | { "type": "turn", event: TurnEvent, };
