// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 画面のヘッダー向けのタスク詳細。`TaskListItem`と同じ工程の数とフォールバックを添え、
 * 一覧とヘッダーで進捗と未設定時の呼び方を揃える。`Task`そのものには足さない:`Task`はモデルへ渡す
 * `task_detail`にも乗るため、混ぜるとモデルがタイトル設定済みと誤解する
 * (docs/spec/rebuild/tools.md「モデルには `title: null` をそのまま見せる」)。
 */
export type TaskDetailView = { steps_done: number, steps_total: number, 
/**
 * `TaskListItem::fallback_label`と同じ。
 */
fallback_label: string | null, id: number, title: string | null, description: string | null, deadline: string | null, archived_at: string | null, deleted_at: string | null, created_at: string, updated_at: string, };
