// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Task = { id: number, title: string | null, description: string | null, deadline: string | null, archived_at: string | null, deleted_at: string | null, created_at: string, updated_at: string, };
