// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * サイドバーの1行。`TaskSummary`に、表示側だけで使うフォールバックを添える。
 * `title`は未設定(null)のまま返し、書き換えない
 * (docs/spec/rebuild/data-model.md「title は TEXT NULL」)。
 */
export type TaskListItem = { 
/**
 * `title`が未設定のときに代わりに表示する、最初のユーザー発言の切り詰め。
 * ユーザー発言がまだ無ければ`None`(その場合の表示は画面側が決める)。
 */
fallback_label: string | null, id: number, title: string | null, deadline: string | null, archived_at: string | null, steps_done: number, steps_total: number, };
