// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ツール呼び出しの上限。設定値そのもの(未設定は`None`)に加え、未設定時に実際に使われる
 * 既定値も渡す。画面はプレースホルダにこれを出すだけで、既定値をTS側に書き写さない(2箇所に
 * 持つと必ずどちらかが古くなる)。
 */
export type ToolSettingsView = { max_rounds_per_turn: number | null, total_timeout_secs: number | null, default_max_rounds_per_turn: number, default_total_timeout_secs: number, };
