// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ツール呼び出しの引数。JSONとして読めなかった場合もアダプタで`Err`にせず、生の文字列の
 * まま上位へ運ぶ。読めない引数は性能の低いモデルでは日常的に起こり、ターンごと止めると
 * principles.md 3節「失敗しても会話を止めない」を割るため。かといって空オブジェクト等へ
 * 置き換えると同節「暗黙の型変換をしない」を割る(引数を伴うツールを引数無しで発火させる)。
 * 実行せずに失敗をモデルへ返す判断は`orchestration::turn`が持つ。
 */
export type ToolArguments = { "status": "valid", value: unknown, } | { "status": "malformed", raw: string, error: string, };
