// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ツール呼び出しの上限(Issue #71)。設定値そのもの(未設定は`None`)に加え、未設定時に
 * 実際に使われる既定値も渡す。画面はプレースホルダにこれを出すだけで、既定値を
 * TS側に書き写さない(2箇所に持つと必ずどちらかが古くなる)。
 */
export type ToolSettingsView = { max_rounds_per_turn: number | null, total_timeout_secs: number | null, default_max_rounds_per_turn: number, default_total_timeout_secs: number, };
