// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 画面に出すツール実行記録。記録はモデルや外部ツールが何を出したかをそのまま確かめるための
 * 表示なので、引数と結果は整形したJSONのまま、見えない文字だけを見える形にして渡す。
 * 閉じた状態で1行に出す引数の要約と失敗の文言も、同じ規則で作って渡す。
 * どの文字が見えないかの判定と、どこで切り詰めるかを画面に写さないため、ここで作る。
 */
export type ToolExecutionView = { 
/**
 * 呼び出したツールの名前。記録から読めなければ`None`。
 */
tool: string | null, arguments: string, result: string, is_error: boolean, 
/**
 * 引数の1行の要約(`キー: 値`を並べたもの。値はJSONの形)。長い値と全体は省略する。
 * 引数が無ければ空。
 */
summary: string, 
/**
 * 失敗の文言の1行(結果の`error`の値)。失敗でなければ`None`。
 */
error: string | null, };
