// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 画面に出すツール実行記録。記録はモデルや外部ツールが何を出したかをそのまま確かめるための
 * 表示なので、引数と結果は整形したJSONのまま、見えない文字だけを見える形にして渡す
 * (architecture.md 10節)。どの文字が見えないかの判定を画面に写さないため、ここで作る。
 */
export type ToolExecutionView = { 
/**
 * 呼び出したツールの名前。記録から読めなければ`None`。
 */
tool: string | null, arguments: string, result: string, is_error: boolean, };
