// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ツール呼び出しの上限。設定値(未設定は`None`)と未設定時の既定値の両方を渡し、画面は
 * 既定値をプレースホルダに出す。
 */
export type ToolSettingsView = { max_rounds_per_turn: number | null, total_timeout_secs: number | null, default_max_rounds_per_turn: number, default_total_timeout_secs: number, };
