// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ツール呼び出しの引数。JSONとして読めなかった場合もアダプタで`Err`にせず、生の文字列の
 * まま上位へ運ぶ(`orchestration::turn`が実行せずに失敗をモデルへ返す)。ターンごと止めると
 * 性能の低いモデルでは会話が続かず、空オブジェクト等に置き換えると引数を伴うツールを
 * 引数無しで発火させるため。
 */
export type ToolArguments = { "status": "valid", value: unknown, } | { "status": "malformed", raw: string, error: string, };
