// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResponseEvent } from "./ResponseEvent";
import type { ToolExecutionView } from "./ToolExecutionView";

/**
 * どのタスクのイベントかは持たない。受け口はターンの呼び出しごとに渡されるので、
 * 呼び出し側が知っている。
 */
export type TurnEvent = { "type": "response", event: ResponseEvent, } | { "type": "tool_executed", id: number, execution: ToolExecutionView, };
